# Generated by Django 5.1.3 on 2024-12-09 12:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='обо мне'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pics/', validators=[users.models.max_size_validator], verbose_name='изображение профиля'),
        ),
    ]
