# Generated by Django 5.1.3 on 2024-12-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',), 'verbose_name': 'Профиль'},
        ),
    ]
