# Generated by Django 5.1.3 on 2024-12-04 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_options_alter_video_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='full_text',
            field=models.TextField(verbose_name='полный текст'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.PositiveIntegerField(verbose_name='временная метка'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.video', verbose_name='видео'),
        ),
    ]
