# Generated by Django 5.1.3 on 2024-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_search_string_alter_rate_quote_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='full_text',
            field=models.TextField(max_length=1000, verbose_name='полный текст'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
    ]
