# Generated by Django 5.1.3 on 2024-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quote_full_text_alter_quote_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='N-4DhlH58Wc', max_length=50),
            preserve_default=False,
        ),
    ]
