# Generated by Django 5.1.3 on 2024-12-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quote_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-id',), 'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
    ]
